<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        // ── Manager ───────────────────────────────────────────────
        User::firstOrCreate(
            ['employee_code' => 'QL00001'],
            [
                'name'                 => 'Quản Lý Hệ Thống',
                'email'                => 'manager@shimada.com.vn',
                'password'             => Hash::make('password'),
                'role'                 => 'manager',
                'department'           => 'Ban Giám đốc',
                'position'             => 'Quản lý hệ thống',
                'annual_leave_balance' => 15,
            ]
        );

        // ── Employees — sourced from tblusers.sql ─────────────────
        // Filter: terminatedate IS NULL or terminatedate >= 2026-03-01
        $employees = [
            ['name'=>'Phan Thị Ngọc Diệu','employee_code'=>'070601-DIEUPTN','email'=>'dieu.phan@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'Phan Thị Thủy','employee_code'=>'080104-THUYPT','email'=>'phanthithuy22981@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Thị Hồng Ngọc','employee_code'=>'080404-NGOCNTH','email'=>'ngoc.nguyen@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Nguyễn Hoàng Phượng','employee_code'=>'090418-PHUONGNH','email'=>'nguyenhoangphuong6423@gmail.com','department'=>'Phòng QC'],
            ['name'=>'Nguyễn Thị Thương','employee_code'=>'090601-THUONGNT','email'=>'thuongnguyenminh24@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Trần Thị Ngọc Thúy','employee_code'=>'090710-THUYTTN','email'=>'thuytrana925@gmail.com','department'=>'Phòng QC'],
            ['name'=>'Nguyễn Thị Mai Phương','employee_code'=>'090916-PHUONGNTM','email'=>'phuong.nguyen@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'Hồ Phúc Đại','employee_code'=>'100316-DAIHP','email'=>'phucdaiht@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Huỳnh Kim Phụng','employee_code'=>'100401-PHUNGHK','email'=>'huynhkimphung8847@gmail.com','department'=>'Phòng QC'],
            ['name'=>'Vũ Kim Thanh','employee_code'=>'100401-THANHVK','email'=>'thanhvu.020484@gmail.com','department'=>'Phòng QC'],
            ['name'=>'Lương Văn Sang','employee_code'=>'110103-SANGLV','email'=>'luongsang1309@gmail.com','department'=>'Phòng Logistics'],
            ['name'=>'Lý Hoàng Kim','employee_code'=>'110316-KIMLH','email'=>'lyhoangkimbd1@gmail.com','department'=>'Phòng QC'],
            ['name'=>'Huỳnh Kim Trang','employee_code'=>'110316-TRANGHK','email'=>'huynhkimtrang2307@gmail.com','department'=>'Phòng QC'],
            ['name'=>'Huỳnh Thị Phương Hiền','employee_code'=>'110401-HIENHTP','email'=>'hien.huynh@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Trần Thị Ngọc Hòa','employee_code'=>'110825-HOATTN','email'=>'hoa.tran@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'Nguyễn Hồng Trung','employee_code'=>'111001-TRUNGNH','email'=>'trangkhang2707@gmail.com','department'=>'Phòng Logistics'],
            ['name'=>'Ngô Mỹ Linh','employee_code'=>'120116-LINHNM','email'=>'linh.ngo@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Trần Thị Thanh Tuyền','employee_code'=>'120402-TUYENTTT','email'=>'1thanh.tuyen271289@gmail.com','department'=>'Phòng QC'],
            ['name'=>'Lê Thị Mừng','employee_code'=>'120418-MUNGLT','email'=>'mung.le@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Nguyễn Chí Thiện','employee_code'=>'120612-THIENNC','email'=>'daminh.chithien@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Hồng Nga','employee_code'=>'120627-NGANH','email'=>'nguyenhongnga290985@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Thị Thản','employee_code'=>'121016-THANNT','email'=>'nguyenthithan742@gmail.com','department'=>'Phòng QC'],
            ['name'=>'Trần Dạ Thảo','employee_code'=>'121203-THAOTD','email'=>'thao.tran@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Huỳnh Thị Kim Ngọc','employee_code'=>'130401-NGOCHTK','email'=>'ngoc.huynh@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Nguyễn Chỉ Ngận','employee_code'=>'140217-NGANNC','email'=>'ngan.nguyenchi@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Thị Thảo','employee_code'=>'140516-THAONT','email'=>'thaogv2525@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Thị Hóa','employee_code'=>'150126-HOANT','email'=>'hoa.nguyen@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Hoàng Thị Hằng','employee_code'=>'150402-HANGHT','email'=>'hthihang97@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Võ Văn Là','employee_code'=>'150907-LAVV','email'=>'vovanla1983.oppo@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Thị Liên','employee_code'=>'160312-LIENNT','email'=>'thilien@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Trần Thị Thanh Nguyên','employee_code'=>'160601-NGUYENTTT','email'=>'nguyen.tran@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Nguyễn Thị Nhung','employee_code'=>'160701-NHUNGNT','email'=>'nhungnguyenthi26091991@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Trần Thị Thanh','employee_code'=>'160701-THANHTT','email'=>'thanhtran.48580@gmail.com','department'=>'Phòng QC'],
            ['name'=>'Nguyễn Thị Tú Trinh','employee_code'=>'160801-TRINHNTT','email'=>'trinh.nguyen@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Nguyễn Công Trí','employee_code'=>'160926-TRINC','email'=>'congtri2474@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Lê Thị Mỹ Luận','employee_code'=>'170214-LUANLTM','email'=>'luan.le@shimada.com.vn','department'=>'Phòng Hành chính'],
            ['name'=>'Trần Huyền Ngân','employee_code'=>'170227-NGANTH','email'=>'ngan.tran@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Thạch Cảnh','employee_code'=>'170403-CANHT','email'=>'thachcanh.09112019@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Hoàng Thị Phương','employee_code'=>'170425-PHUONGHT','email'=>'hvo05020@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Lê Thị Chuyên','employee_code'=>'170503-CHUYENLT','email'=>'chuyen.le@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Nguyễn Thị Hiếu','employee_code'=>'170510-HIEUNT','email'=>'hieu.nguyen@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Bùi Thái Vy Khanh','employee_code'=>'170717-KHANHBTV','email'=>'khanh.bui@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'Trần Vũ Phương','employee_code'=>'171002-PHUONGTV','email'=>'343777phuong@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Đặng Hoài Ngọc','employee_code'=>'181203-NGOCDH','email'=>'danghoaingocdmx32@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Mã Ngọc Xuyên','employee_code'=>'190301-XUYENMN','email'=>'mangocxuyen92@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Viết Thắng','employee_code'=>'190325-THANGNV','email'=>'nguyenvietthang483@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Thị Thúy Ngân','employee_code'=>'190401-NGANNTT','email'=>'ngan.nguyen@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Trần Thị Hồng Thuận','employee_code'=>'190506-THUANTTH','email'=>'thuan.tran@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Trần Thị Cẩm Tiến','employee_code'=>'190516-TIENTTC','email'=>'nguyenthicamtien240397@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Phạm Kim Hồng','employee_code'=>'190909-HONGPK','email'=>'hong.pham@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Thái Thị Thanh Hà','employee_code'=>'191001-HATTT','email'=>'ha.thai@shimada.com.vn','department'=>'Phòng Hành chính'],
            ['name'=>'Bùi Thị Lan','employee_code'=>'191007-LANBT','email'=>'lan.bui@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Nguyễn Anh Hoài Thương','employee_code'=>'200102-THUONGNAH','email'=>'thuong.nguyen@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'KOJIMA RIKUYA','employee_code'=>'200301-KOJIMA-RIKUYA','email'=>'kojima.rikuya@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Nguyễn Thị Huệ','employee_code'=>'200302-HUENT','email'=>'hue.nguyen@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Nguyễn Thị Ngọc Quỳnh','employee_code'=>'200304-QUYNHNTN','email'=>'quynh.nguyen@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Vũ Mai Nhật Anh','employee_code'=>'200622-ANHVMN','email'=>'anh.vu@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'Phan Hồng Việt','employee_code'=>'200903-VIETPH','email'=>'phanviet6879@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Trần Minh Nhựt','employee_code'=>'200921-NHUTTM','email'=>'nhut04737@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Bùi Thị Hồng Thủy','employee_code'=>'201021-THUYBTH','email'=>'thuy.bui@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Nguyễn Huy Hoàng','employee_code'=>'201116-HOANGNH','email'=>'nguyenhuyhoang2635@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Trần Ngọc Dung','employee_code'=>'210125-DUNGTN','email'=>'dung.tran@shimada.com.vn','department'=>'Phòng Hành chính'],
            ['name'=>'Phạm Tuấn Trí','employee_code'=>'210217-TRIPT','email'=>'johnnytripham2309@gmail.com','department'=>'Phòng Logistics'],
            ['name'=>'Võ Minh Khang','employee_code'=>'210308-KHANGVM','email'=>'minhkhang21112000@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Lê Thị Thu Hà','employee_code'=>'210318-HALTT','email'=>'ha.le@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Phạm Ngọc Hải','employee_code'=>'210412-HAIPN','email'=>'haip0922@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Minh Tú','employee_code'=>'210419-TUNM','email'=>'tuto30121996@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Võ Trọng Nhân','employee_code'=>'210504-NHANVT','email'=>'votrongnhan2019@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'SAKAGAMI AKIRA','employee_code'=>'211208-SAKAGAMI-AKIR','email'=>'sakagami.akira@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Nguyễn Phước Định Quốc','employee_code'=>'220221-QUOCNPD','email'=>'nguyenphuocdinhquoc1@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Đặng Văn Năm','employee_code'=>'220606-NAMDV','email'=>'dangnam241091@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Trần Công Minh','employee_code'=>'220613-MINHTC','email'=>'trancongminh091120@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Trần Thanh Tuấn','employee_code'=>'220613-TUANTT','email'=>'tranthanhtuan7386@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Thị Nhung','employee_code'=>'220801-NHUNGNT','email'=>'nhung.nguyen@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Trần Thị Của','employee_code'=>'220808-CUATT','email'=>'cua.tran@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Trần Trung Hiếu','employee_code'=>'221101-HIEUTT','email'=>'hieut1558@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Võ Thị Kim Hồng','employee_code'=>'221101-HONGVTK','email'=>'hong.vo@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Nguyễn Thị Thuỳ Vân','employee_code'=>'221108-VANNTT','email'=>'van.nguyen@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'Liễu Kim Tuyết','employee_code'=>'230105-TUYETLK','email'=>'tuyet.lieu@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Trương Quang Phương','employee_code'=>'230213-PHUONGTQ','email'=>'fang.truong@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Nguyễn Thị Ly','employee_code'=>'230403-LYNT','email'=>'ly.nguyen@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Phạm Thúy Vân','employee_code'=>'230417-VANPT','email'=>'van.pham@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'MATSUZAWA YO','employee_code'=>'230508-MATSUZAWA-YO','email'=>'matsuzawa.yo@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Võ Diệu Vinh','employee_code'=>'230508-VINHVD','email'=>'vinh.vo@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Trần Thị Dương','employee_code'=>'230605-DUONGTT','email'=>'sunny.tran@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Trần Thục Kiêu','employee_code'=>'230605-KIEUTT','email'=>'kate.tran@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Nguyễn Thị Thanh Tuyền','employee_code'=>'230703-TUYENNTT','email'=>'tuyen.nguyen@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Nguyễn Nhật Vũ','employee_code'=>'230918-VUNN','email'=>'nguyennhatvu1292@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'SHIMADA TAKASHI','employee_code'=>'231021-SHIMADA-TAKAS','email'=>'shimada.takashi@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Võ Phạm Nhựt Duy','employee_code'=>'240219-DUYVPN','email'=>'duy.vo@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Hoàng Thị Hương Hà','employee_code'=>'240219-HAHTH','email'=>'ha.hoang@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'Nguyễn Ngọc Hồng Phúc','employee_code'=>'240219-PHUCNNH','email'=>'tokie.nguyen@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'YOSHISUE AKIRA','employee_code'=>'240219-YOSHISUE-AKIR','email'=>'yoshisue.akira@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'TSUDA KAZUKI','employee_code'=>'240225-TSUDA-KAZUKI','email'=>'tsuda.kazuki@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Nguyễn Viết Linh','employee_code'=>'240318-LINHNV','email'=>'linhnguyendmx2019@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Lê Hữu Thăng Long','employee_code'=>'240319-LONGLHT','email'=>'lelong.2000dt@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Thị Thu Phương','employee_code'=>'240415-PHUONGNTT','email'=>'tphuong.nguyen@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Phạm Văn Quí','employee_code'=>'240506-QUIPV','email'=>'phamqui1992van@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Thị Mỹ Thành','employee_code'=>'240507-THANHNTM','email'=>'thanh.nguyen@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Đỗ Thị Hồng','employee_code'=>'240520-HONGDT','email'=>'hong.do@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Lê Thị Thu Thảo','employee_code'=>'240520-THAOLTT','email'=>'lily.le@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Đinh Ngọc Chiến','employee_code'=>'240523-CHIENDN','email'=>'doichannan97@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Hoàng Hồng Lê','employee_code'=>'240617-LEHH','email'=>'le.hoang@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Văn Mỹ Anh','employee_code'=>'240701-ANHVM','email'=>'keny.van@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Phạm Thị Lâm Tuyền','employee_code'=>'240708-TUYENPTL','email'=>'tuyen.pham@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'Phan Văn Lộc','employee_code'=>'240717-LOCPV','email'=>'phanvanloc238995@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Phạm Thị Kim Ngọc','employee_code'=>'240717-NGOCPTK','email'=>'ngoc.pham@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Bùi Thị Xuân Hoa','employee_code'=>'240806-HOABTX','email'=>'dl9hoa.bui@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Đoàn Hữu Phú','employee_code'=>'240806-PHUDH','email'=>'dl9phu.doan@shimada.com.vn','department'=>'Phòng Hành chính'],
            ['name'=>'Trần Kiều Trang','employee_code'=>'240806-TRANGTK','email'=>'dl9trang.tran@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Nguyễn Tâm','employee_code'=>'240904-TAMN','email'=>'henry.nguyen@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Huỳnh Văn Gấm','employee_code'=>'240917-GAMHV','email'=>'gamhuynhvan9@gmail.com','department'=>'Phòng Logistics'],
            ['name'=>'Trịnh Thị Thúy Vân','employee_code'=>'240917-VANTTT','email'=>'van.trinh@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Lê Minh Khang','employee_code'=>'240925-KHANGLM','email'=>'lekhang240805@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Ngọc Phương Uyên','employee_code'=>'240925-UYENNNP','email'=>'up9182521@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Tuấn Hào','employee_code'=>'241001-HAONT','email'=>'hao.nguyen@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Võ Thị Hồng Luyến','employee_code'=>'241017-LUYENVTH','email'=>'dl9luyen.vo@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Lâm Hửu Duy','employee_code'=>'241106-DUYLH','email'=>'lamhuuduy1510@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Trương Tấn Tài','employee_code'=>'241106-TAITT','email'=>'tai94610@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'KITAOKA SHINYA','employee_code'=>'241209-SHINYAK','email'=>'kitaoka.shinya@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'KATAYAMA MASAHIDE','employee_code'=>'241216-KATAYAMAM','email'=>'katayama.masahide@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Phan Kim Ý','employee_code'=>'250102-YPK','email'=>'kimy.phan@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Đặng Thị Thủy','employee_code'=>'250113-THUYDT','email'=>'thuy.dang@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Lê Ngọc Bảo Trân','employee_code'=>'250113-TRANLNB','email'=>'tran.le@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Huỳnh Như','employee_code'=>'250203-NHUH','email'=>'nhu.huynh@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Nguyễn Quốc Phi','employee_code'=>'250203-PHINQ','email'=>'quocphi0711@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Tô Trọng Hiếu','employee_code'=>'250217-HIEUTT','email'=>'hieudeptrai170599@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Huỳnh Thanh Hòa','employee_code'=>'250217-HOAHT','email'=>'thanhhoa010320@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Ngụy Khắc Tịnh','employee_code'=>'250218-TINHNK','email'=>'nguykhactinh1983@gmail.com','department'=>'Phòng QC'],
            ['name'=>'TAKASE REIKA','employee_code'=>'250224-REIKAT','email'=>'takase.reika@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Vương Phúc Dĩ Khang','employee_code'=>'250304-KHANGVPD','email'=>'vuongphuckhangdi@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Ngô Thị Mỹ Anh','employee_code'=>'250317-ANHNTM','email'=>'sam.ngo@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'Nguyễn Thị Trúc Đào','employee_code'=>'250318-DAONTT','email'=>'ndao99338@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Huỳnh Đặng Thanh Huyền','employee_code'=>'250318-HUYENHDT','email'=>'huynhdangthanhhuyen@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Mai Thùy Dương','employee_code'=>'250324-DUONGMT','email'=>'thuyduongmai191919@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Trần Văn Tiến','employee_code'=>'250324-TIENTV','email'=>'trananhtienn01@gmail.com','department'=>'Phòng QC'],
            ['name'=>'Nguyễn Thị Hải Yến','employee_code'=>'250324-YENNTH','email'=>'yennailmimakeup@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Hoàng Thị Hằng','employee_code'=>'250401-HANGHT','email'=>'hoanghang526299@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Phạm Thị Hồng Vân','employee_code'=>'250401-VANPTH','email'=>'hongvan.pham@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'Ngô Thị Quỳnh Thơ','employee_code'=>'250421-THONTQ','email'=>'dl9tho.ngo@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Tô Kim Tiên','employee_code'=>'250505-TIENTK','email'=>'tien.to@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'YOSHIOKA YUKI','employee_code'=>'250510-YUKIY','email'=>null,'department'=>'Ban Giám đốc'],
            ['name'=>'Huỳnh Duy Khánh','employee_code'=>'250519-KHANHHD','email'=>'khanhxalu999@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Thị Thu Uyên','employee_code'=>'250528-UYENNTT','email'=>'uyen.nguyen@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'SUGITANI RYOTARO','employee_code'=>'250531-RYOTAROS','email'=>null,'department'=>'Ban Giám đốc'],
            ['name'=>'Nguyễn Thị Xuân Hương','employee_code'=>'250602-HUONGNTX','email'=>'huong.nguyen@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Nguyễn Thị Thu Hằng','employee_code'=>'250603-HANGNTT','email'=>'dl9hang.nguyen@shimada.com.vn','department'=>'Phòng Hành chính'],
            ['name'=>'Huỳnh Văn Tuấn Khang','employee_code'=>'250603-KHANGHVT','email'=>'locthanh166@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Trần Kim Oanh','employee_code'=>'250603-OANHTK','email'=>'trankimoanh.1664@gmail.com','department'=>'Phòng QC'],
            ['name'=>'Nguyễn Minh Tuấn','employee_code'=>'250603-TUANNM','email'=>'tuannguyen.011020@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'SERA TAKENORI','employee_code'=>'250628-TAKENORIS','email'=>'sera.takenori@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Nguyễn Thị Thanh Giang','employee_code'=>'250701-GIANGNTT','email'=>'giang.nguyen@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Đoàn Minh Phương','employee_code'=>'250821-PHUONGDM','email'=>'doan9404@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Minh Tuấn','employee_code'=>'250821-TUANNM','email'=>'minhtuan41195@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Lê Thành Tuấn','employee_code'=>'250903-TUANLT','email'=>'le4117163@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Võ Thị Thiên Ngọc','employee_code'=>'250918-NGOCVTT','email'=>'ngoc.vo@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Trần Ngọc Quyên','employee_code'=>'250922-QUYENTN','email'=>'quyen.tran@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'Huỳnh Thị Kim Ngân','employee_code'=>'250929-NGANHTK','email'=>'huynhkimngan0907@gmail.com','department'=>'Phòng Kinh doanh'],
            ['name'=>'Võ Duy Khánh','employee_code'=>'251001-KHANHVD','email'=>'duykhanh1664@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Thị Kiều','employee_code'=>'251001-KIEUNT','email'=>'dl9kieu.nguyen@shimada.com.vn','department'=>'Phòng IT'],
            ['name'=>'Trần Quốc Bảo','employee_code'=>'251002-BAOTQ','email'=>'embuonkhong3@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Vũ Luân','employee_code'=>'251013-LUANNV','email'=>'lmn2215590@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Võ Thanh Đông','employee_code'=>'251020-DONGVT','email'=>'higashivo91@gmail.com','department'=>'Ban Giám đốc'],
            ['name'=>'Đặng Thị Thu Loan','employee_code'=>'251028-LOANDTT','email'=>'dangloan1712@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Thanh Tài','employee_code'=>'251028-TAINT','email'=>'thanhtaifpt1611@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Trần Thị Kim Ngân','employee_code'=>'251104-NGANTTK','email'=>'ttkn27th9o7@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Thị Hồng','employee_code'=>'251110-HONGNT','email'=>'nguyenhong.dn011@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Nguyễn Lê Mai Linh','employee_code'=>'251117-LINHNLM','email'=>'linh.nguyen@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'Nguyễn Thị Thu Hiền','employee_code'=>'260105-HIENNTT','email'=>'hien.nguyen@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'Trần Phước Lộc','employee_code'=>'260107-LOCTP','email'=>'phuocloc19251925@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Ngô Văn Hiệp','employee_code'=>'260120-HIEPNV','email'=>'hiepngo761310@gmail.com','department'=>'Phòng Nhân sự'],
            ['name'=>'Đặng Thị Thùy Dung','employee_code'=>'260223-DUNGDTT','email'=>'dung.dang@shimada.com.vn','department'=>'Phòng Nhân sự'],
            ['name'=>'Nguyễn Ngọc Hương Lan','employee_code'=>'260223-LANNNH','email'=>'lan.nguyen@shimada.com.vn','department'=>'Phòng Kinh doanh'],
            ['name'=>'YAGI KOJI','employee_code'=>'260301-KOJIY','email'=>'yagi_koji@shimada.com.vn','department'=>'Ban Giám đốc'],
            ['name'=>'Phạm Trí Nghĩa','employee_code'=>'260304-NGHIAPT','email'=>null,'department'=>'Xưởng sản xuất'],
            ['name'=>'Hà Phong Phú','employee_code'=>'260304-PHUHP','email'=>'haphongphu.31051998@gmail.com','department'=>'Xưởng sản xuất'],
            ['name'=>'Lê Văn Sang','employee_code'=>'260304-SANGLV','email'=>'levansang6991@gmail.com','department'=>'Xưởng sản xuất'],
        ];

        $defaultPassword = Hash::make('password');

        foreach ($employees as $emp) {
            User::firstOrCreate(
                ['employee_code' => $emp['employee_code']],
                [
                    'name'                 => $emp['name'],
                    'email'                => $emp['email'],
                    'password'             => $defaultPassword,
                    'role'                 => 'employee',
                    'department'           => $emp['department'],
                    'position'             => null,
                    'annual_leave_balance' => 12,
                ]
            );
        }
    }
}
